# /* ---- 💫 https://github.com/Akashio28 💫 ---- */  #
# as per Hyprland wiki: hyprland-qt-support provides a QML style for hypr* qt6 apps                                                         

rounding = 2

border_size = 0

reduce_motion = false