-- /* ---- 💫 https://github.com/Acacio28 ---- */
-- Generated by HyprMod GUI -- do not edit manually

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 0,
        resize_on_border = false,
        extend_border_grab_area = 5,
        hover_icon_on_border = true,
    },
    decoration = {
        rounding = 15,
        rounding_power = 2.0,
        blur = {
            size = 11,
            passes = 2,
            xray = false,
            noise = 0.012,
        },
        shadow = {
            enabled = true,
            range = 13,
            render_power = 4,
            offset = "2 1",
            scale = 1.0,
            color = "0xff3d3846",
            color_inactive = "0xff3d3846",
        },
    },
    misc = {
        vrr = 2,
    },
})


























































































































































































































































































hl.curve("easeOut", { type = "bezier", points = { {0.0, 0.0}, {0.58, 1.0} } })

hl.animation({ leaf = "windowsMove", enabled = true, speed = 6.0, bezier = "easeOut", style = "slide" })
hl.animation({ leaf = "layers",      enabled = true, speed = 7.5, bezier = "default", style = "slide" })

-- Re-apply config on lid open / monitor hotplug so GUI settings survive
hl.on("monitor.added", function()
    hl.exec_cmd("hyprctl reload")
end)
