-- /* ---- 💫 https://github.com/Acacio28 ---- */
-- Generated by HyprMod GUI -- do not edit manually

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 4,
        border_size = 0,
        resize_on_border = true,
        extend_border_grab_area = 0,
        hover_icon_on_border = true,
        col = {
            active_border = "0xffffffff",
            inactive_border = "0xffffffff",
        },
    },
    decoration = {
        rounding = 15,
        rounding_power = 3.0,
        blur = {
            size = 5,
            passes = 5,
            noise = 0.012,
        },
        shadow = {
            enabled = true,
            range = 10,
            render_power = 4,
            offset = "3 3",
            scale = 1.0,
            color = "0xff5e5c64",
            color_inactive = "0xff5e5c64",
        },
    },
    misc = {
        vrr = 2,
    },
})
























































































































hl.curve("easeOut", { type = "bezier", points = { {0.0, 0.0}, {0.58, 1.0} } })

hl.animation({ leaf = "windowsMove", enabled = true, speed = 6.0, bezier = "easeOut", style = "slide" })
hl.animation({ leaf = "layers",      enabled = true, speed = 7.5, bezier = "default", style = "slide" })

-- Re-apply config on lid open / monitor hotplug so GUI settings survive
hl.on("monitor.added", function()
    hl.exec_cmd("hyprctl reload")
end)
