-- Generated by HyprMod

hl.env("XCURSOR_THEME", "Breeze_Light")
hl.env("XCURSOR_SIZE", "24")

hl.config({
    general = {
        allow_tearing    = false,
        border_size      = 2,
        col = {
            active_border   = "0xff613583",
            inactive_border = "0xffc0bfbc",
        },
        layout = "dwindle",
    },
    input = {
        natural_scroll = false,
        scroll_factor  = 0.8,
    },
})

hl.curve("easeOut", { type = "bezier", points = { {0.0, 0.0}, {0.58, 1.0} } })

hl.animation({ leaf = "windowsMove", enabled = true, speed = 6.0, bezier = "easeOut", style = "slide" })
hl.animation({ leaf = "layers",      enabled = true, speed = 7.5, bezier = "default", style = "slide" })
