-- /* ---- 💫 https://github.com/Acacio28 ---- */
-- Generated by nwg-displays on 2026-06-03 at 13:29:55. Do not edit manually.

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@59.93",
    position = "0x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1200@59.95",
    position = "1920x0",
    scale    = 1.0,
})
