-- /* ---- 💫 https://github.com/Acacio28 ---- */
-- Auto-generated by wallust — do not edit manually.

local M = {}

M.background = "{{background | strip}}"
M.foreground = "{{foreground | strip}}"
M.color0  = "{{color0 | strip}}"
M.color1  = "{{color1 | strip}}"
M.color2  = "{{color2 | strip}}"
M.color3  = "{{color3 | strip}}"
M.color4  = "{{color4 | strip}}"
M.color5  = "{{color5 | strip}}"
M.color6  = "{{color6 | strip}}"
M.color7  = "{{color7 | strip}}"
M.color8  = "{{color8 | strip}}"
M.color9  = "{{color9 | strip}}"
M.color10 = "{{color10 | strip}}"
M.color11 = "{{color11 | strip}}"
M.color12 = "{{color12 | strip}}"
M.color13 = "{{color13 | strip}}"
M.color14 = "{{color14 | strip}}"
M.color15 = "{{color15 | strip}}"

return M
