# /* ---- 💫 https://github.com/Acacio28 ---- */
# /* wallust template - colors-kitty */

foreground         #F1E4F7
background         #04000D
cursor             #A795B4

active_tab_foreground     #04000D
active_tab_background     #F1E4F7
inactive_tab_foreground   #F1E4F7
inactive_tab_background   #04000D

active_border_color   #F1E4F7
inactive_border_color #04000D
bell_border_color     #2F2347

color0      #04000D
color1		#2F2347
color2		#463455
color3		#765670
color4		#7A5973
color5		#7D5C76
color6		#A186AE
color7		#E2D1EB
color8		#9E92A5
color9		#3E2E5F
color10		#5E4571
color11		#9D7295
color12		#A37799
color13		#A67B9E
color14		#D6B3E8
color15		#E2D1EB
