# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(04000D)
$foreground = rgb(F1E4F7)
$color0 = rgb(04000D)
$color1 = rgb(2F2347)
$color2 = rgb(463455)
$color3 = rgb(765670)
$color4 = rgb(7A5973)
$color5 = rgb(7D5C76)
$color6 = rgb(A186AE)
$color7 = rgb(E2D1EB)
$color8 = rgb(9E92A5)
$color9 = rgb(3E2E5F)
$color10 = rgb(5E4571)
$color11 = rgb(9D7295)
$color12 = rgb(A37799)
$color13 = rgb(A67B9E)
$color14 = rgb(D6B3E8)
$color15 = rgb(E2D1EB)
