# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1314)
$foreground = rgb(DDDDDD)
$color0 = rgb(443A3B)
$color1 = rgb(240407)
$color2 = rgb(2A0B0E)
$color3 = rgb(383838)
$color4 = rgb(4E3D3F)
$color5 = rgb(6D6869)
$color6 = rgb(777676)
$color7 = rgb(C7C6C6)
$color8 = rgb(8B8B8B)
$color9 = rgb(31050A)
$color10 = rgb(370F13)
$color11 = rgb(4B4A4A)
$color12 = rgb(685254)
$color13 = rgb(918B8B)
$color14 = rgb(9F9E9E)
$color15 = rgb(C7C6C6)
